engines:
  duplication:
       enabled: true
       config:
         languages:
           javascript:
             mass_threshold: 80
  eslint:
    enabled: false
    channel: "eslint-3"
    config:
        extensions:
        - .js
        - .jsx

ratings:
   paths:
   - "**.js"
   - "**.jsx"
