engines:
  duplication:
       enabled: true
       config:
         languages:
           javascript:
             mass_threshold: 80
  eslint:
    enabled: false
    channel: "eslint-4"
    config:
        extensions:
        - .js
        - .jsx

ratings:
   paths:
   - "**.js"
   - "**.jsx"

exclude_paths:
- "plugins/album/public/lib/color-thief.js"
- "plugins/album/test/cases.js"
- "plugins/editAlbum/public/lib/json_to_xml.js"

