export const LIST_DIRECTORY_REQUEST = 'app/Walk/LIST_DIRECTORY_REQUEST';
export const LIST_DIRECTORY_SUCCESS = 'app/Walk/LIST_DIRECTORY_SUCCESS';
export const LIST_DIRECTORY_FAILURE = 'app/Walk/LIST_DIRECTORY_FAILURE';
