export const LIST_DIRECTORY_REQUEST = 'app/Walk/LIST_DIRECTORY_REQUEST';
export const LIST_DIRECTORY_SUCCESS = 'app/Walk/LIST_DIRECTORY_SUCCESS';
export const LIST_DIRECTORY_FAILURE = 'app/Walk/LIST_DIRECTORY_FAILURE';
export const RESIZE_IMAGES_REQUEST = 'app/Walk/RESIZE_IMAGES_REQUEST';
export const RESIZE_IMAGES_SUCCESS = 'app/Walk/RESIZE_IMAGES_SUCCESS';
export const RESIZE_IMAGES_FAILURE = 'app/Walk/RESIZE_IMAGES_FAILURE';
